from elk.utils.testing import TestCase, mock_request
from history.models import PaymentEvent


class TestEvent(TestCase):
    fixtures = ('crm', 'products', 'lessons')
    TEST_PRODUCT_ID = 1

    def test_storing_request(self):
        """
        Unit test for populating log entry model with request.
        """
        mocked_request = mock_request()
        ev = PaymentEvent()
        ev._HistoryEvent__store_request(mocked_request)

        # Assertions are based on fixtures, generated by elk.utils.testing.mock_request
        self.assertEqual(ev.is_mobile, mocked_request.user_agent.is_mobile)
        self.assertEqual(ev.is_tablet, mocked_request.user_agent.is_tablet)
        self.assertEqual(ev.is_pc, mocked_request.user_agent.is_pc)

        self.assertEqual(ev.browser_family, 'Mobile Safari')
        self.assertEqual(ev.browser_version, '5.2')
        self.assertEqual(ev.os_family, 'WinXP')
        self.assertEqual(ev.os_version, '5.3')
        self.assertEqual(ev.device, 'iPhone')

        self.assertEqual(ev.raw_useragent, 'WinXP; U/16')
        self.assertEqual(ev.ip, '127.0.0.5')
