# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrived', models.DateTimeField(auto_now_add=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('starting_level', models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1'), ('A2', 'A2'), ('B2', 'B2'), ('C2', 'C2'), ('A3', 'A3'), ('B3', 'B3'), ('C3', 'C3')], db_index=True, default='A1', max_length=2)),
                ('current_level', models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1'), ('A2', 'A2'), ('B2', 'B2'), ('C2', 'C2'), ('A3', 'A3'), ('B3', 'B3'), ('C3', 'C3')], db_index=True, default='A1', max_length=2)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer_email', models.EmailField(default='', max_length=254)),
                ('first_name', models.CharField(default='', max_length=140)),
                ('last_name', models.CharField(default='', max_length=140)),
            ],
        ),
    ]
