# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_level',
            field=models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1'), ('A2', 'A2'), ('B2', 'B2'), ('C2', 'C2'), ('A3', 'A3'), ('B3', 'B3'), ('C3', 'C3')], db_index=True, default='A1', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='starting_level',
            field=models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1'), ('A2', 'A2'), ('B2', 'B2'), ('C2', 'C2'), ('A3', 'A3'), ('B3', 'B3'), ('C3', 'C3')], db_index=True, default='A1', max_length=2),
        ),
    ]
