# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160627_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='customer_last_name',
        ),
    ]
