# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20160628_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_first_name',
            field=models.CharField(max_length=140, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_last_name',
            field=models.CharField(max_length=140, verbose_name='Last name'),
        ),
    ]
