# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def insert_inernal_source(apps, schema_editor):
    CustomerSource = apps.get_model('crm', 'CustomerSource')

    internal_src = CustomerSource(
        name='internal'
    )
    internal_src.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20160628_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.RunPython(insert_inernal_source),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crm.CustomerSource'),
            preserve_default=False,
        ),
    ]
