# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_auto_20160624_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinaryLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('internal_name', models.CharField(max_length=140)),
                ('duration', models.DurationField()),
                ('description', django_markdown.models.MarkdownField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('payment_date', models.DateTimeField()),
                ('name', models.CharField(max_length=140)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
                ('ordinary_lessons', models.ManyToManyField(to='products.OrdinaryLesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
