# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonWithNative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('internal_name', models.CharField(max_length=140)),
                ('duration', models.DurationField()),
                ('description', django_markdown.models.MarkdownField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('payment_date', models.DateTimeField()),
                ('cost', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='subscription1',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='subscription1',
            name='ordinary_lessons',
        ),
        migrations.DeleteModel(
            name='Subscription1',
        ),
    ]
