# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160624_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product1',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='product1',
            name='internal_name',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
