# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160624_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='lessons_with_native',
            field=models.ManyToManyField(to='products.LessonWithNative'),
        ),
        migrations.AddField(
            model_name='product1',
            name='ordinary_lessons',
            field=models.ManyToManyField(to='products.OrdinaryLesson'),
        ),
    ]
