# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160624_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(42)),
        ),
        migrations.AlterField(
            model_name='lessonwithnative',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 1800)),
        ),
        migrations.AlterField(
            model_name='ordinarylesson',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 1800)),
        ),
    ]
